// actionTypes.js
export const UPDATE_CART_COUNT = 'UPDATE_CART_COUNT';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const SET_SELECTED_SERVICE = 'SET_SELECTED_SERVICE';
export const RESET_CART_COUNT = 'RESET_CART_COUNT';